mysite/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
   # path('', views.post_list, name='post_list'),
    path('', views.PostListView.as_view(), name='post_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.post_detail, name='post_detail'),
    path('<int:post_id>/share/', views.post_share, name='post_share'),
    path('tag/<slug:tag_slug>/', views.post_list, name='post_list_by_tag'),

]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/blog/models.py
from django.db import models

# Create your models here.
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager


class Post(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published')
    )

    title = models.CharField(max_length=250, verbose_name='Назва поста')
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_posts',
                               verbose_name='Автор')

    tags = TaggableManager()

    short_description = models.CharField(max_length=400, verbose_name='Короткий опис')
    publish = models.DateTimeField(default=timezone.now, verbose_name='Дата публікації')
    created = models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')
    updated = models.DateTimeField(auto_now=True, verbose_name='Дата оновлення')
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='draft',
                              verbose_name='Статус публікації')
    image = models.ImageField(upload_to='product_images/', blank=False, verbose_name='Зображення')

    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail', args=[self.publish.year,
                                                 self.publish.month,
                                                 self.publish.day,
                                                 self.slug])


def save_images(instance, filename):
    post_id = instance.post.id
    return 'gallery_images/{}/{}'.format(post_id, filename)


class PostPoint(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, default=None)
    post_point_text = models.TextField(verbose_name='Пункт поста')
    post_images = models.ImageField(upload_to=save_images, blank=True, verbose_name='Зображення поста'),

    def __str__(self):
        return 'Пункт поста {}'.format(self.post.title)

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return 'Коментар написано {} про {}'.format(self.name, self.post)

mysite/blog/forms.py
from django import forms
class CommentForm(forms.Form):
    name = forms.CharField(max_length=25, widget=forms.TextInput(attrs={'class': 'form-control',
                                                                        'id': 'nameInput'}))
    email = forms.EmailField(widget=forms.TextInput(attrs={'class': 'form-control',
                                                           'id': 'exampleInputEmail',
                                                           'aria-dscribedby': 'emailHelp'}))

    comment = forms.CharField(required=False, widget=forms.Textarea(attrs={'class': 'form-control', 'id': 'commets',
                                                                           'rows': '3'}))


class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25, widget=forms.TextInput(attrs={'class': 'form-control',
                                                                        'id': 'nameInput'}))
    email = forms.EmailField(widget=forms.TextInput(attrs={'class': 'form-control',
                                                             'id': 'exampleInputEmail',
                                                             'aria-describedby': 'emailHelp'}))
    to = forms.EmailField(widget=forms.TextInput(attrs={'class': 'form-control',
                                                        'id': 'emailTo'}))
    comment = forms.CharField(required=False, widget=forms.Textarea(attrs={'class': 'form-control','id': 'commets',
                                                                    'rows': '3'}))

mysite/blog/views.py
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.shortcuts import render, get_object_or_404

# Create your views here.
from .models import Post, PostPoint, Comment
from django.views.generic import ListView
from .forms import EmailPostForm, CommentForm
from django.core.mail import send_mail
from taggit.models import Tag
from django.db.models import Count


def post_share(request, post_id):
    post = get_object_or_404(Post, id=post_id, status='published')
    sent = False
    if request.method == 'POST':
        form = EmailPostForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data

            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = '{} ({}) recommends you reading "()"'.format(cd['name'], cd['email'], post.title)
            message = 'Read "{}" at {} \n\n{}\'s comments: {}'.format(post.title,
                                                                      post_url, cd['name'], cd['comment'])
            send_mail(subject, message, 'admin@gmail.com', [cd['to']])
            sent = True

    else:
        form = EmailPostForm()

    return render(request, 'blog/post/share.html', {'post': post, 'form': form, 'sent': sent})


def post_list(request, tag_slug=None):
    object_list = Post.objects.all()

    tag = None
    if tag_slug:
        tag= get_object_or_404(Tag, tag_slug=None)
        object_list = object_list.filter(tags__in=[tag])

    paginator = Paginator(object_list, 3)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)

    return render(request, 'blog/post/list.html', {'page': page, 'posts': posts, 'tag': tag})



class PostListView(ListView):
    queryset = Post.objects.all()
    context_object_name = 'posts'
    paginate_by = 1
    template_name = 'blog/post/list.html'

def post_detail(request, year, month, day, post):
    post_object = get_object_or_404(Post, slug=post, status='published',
                                    publish__year=year,
                                    publish__month=month,
                                    publish__day=day)

    post_points = PostPoint.objects.filter(post=post_object)

    comments = post_object.comments.filter(active=True)
    new_comment = None
    if request.method == 'POST':
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            cd = comment_form.cleaned_data
            new_comment = Comment(post=post_object, name=cd['name'], email=cd['email'], body=cd['comment'])
            new_comment.save()

    else:
        comment_form = CommentForm()

    post_tags_ids = post_object.tags.value_list('id', flat=True)
    similar_posts = Post.objects.Filter(tags__in=post_tags_ids, status='published').exclude(id=post_object.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags', '-publish')[:4]

    return render(request, 'blog/post/detail.html', {'post': post_object,
                                                                        'post_points': post_points,
                                                                        'comments': comments,
                                                                        'new_comment': new_comment,
                                                                        'comment_form': comment_form,
                                                                        'similar_posts': similar_posts})

mysite/blog/templates/blog/base.html
{% comment %} {% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock title %}</title>
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
</head>
<body>
    <div id='content'>
        {% block content %}
        {% endblock content %}     
    </div>
    <div id='sidebar'>
        <h2>My blog</h2>
        <p>This is my blog.</p>
    </div>

</body>
</html> {% endcomment %}


{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock title %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
</head>
  <body>
    {% block navbar %}
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">Navbar</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="#">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Link</a>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Dropdown
                </a>
                <ul class="dropdown-menu">
                  <li><a class="dropdown-item" href="#">Action</a></li>
                  <li><a class="dropdown-item" href="#">Another action</a></li>
                  <li><hr class="dropdown-divider"></li>
                  <li><a class="dropdown-item" href="#">Something else here</a></li>
                </ul>
              </li>
              <li class="nav-item">
                <a class="nav-link disabled" aria-disabled="true">Disabled</a>
              </li>
            </ul>
            <form class="d-flex" role="search">
              <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
              <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
          </div>
        </div>
      </nav>
    {% endblock navbar %}
    {% block content %}
        <h1>Content</h1>
    {% endblock content %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>
  </body>
</html>

mysite/blog/templates/blog/post/detail.html
{% extends "blog/base.html"%}
{% block title %}
    {{ post.title }}
{% endblock title %}
{% block content %}

<div class="container my-3">
        <div class="card-deck">
            <div class="card">
                <img src="{{ MEDIA_ULR }}{{ post.image.ulr }}" class="card-img-top" alt="...">
                <div class="card-body">
                        <h5 class="card-title">{{ post.title}}</h5>
                        <p class="card-text">{{ post.short_description}}</p>
                        <p>
                            <a href="{% url 'blog:post_share' post.id %}">Поділитися постом</a>
                        <p/>
                </div>
                {% for post_point in post_points %}
                    <h5 class="card-title">{{ post_point.post_point_header}}</h5>
                    {% if post_point.post_image %}
                        <img src="{{ MEDIA_URL }}{{ post_point.post_image.url }}"
                        class="card-img-top" alt="..." style="width: 500px">
                    {% endif %}
                    {% if post_point.post_point_header == "Інгредієнти" %}
                        <pre class="card-text">{{ post_point.post_point_text}}</pre>

                    {% else %}
                        <p class="card-text">{{ post_point.post_point_text }}</p>

                    {% endif %}
                </div>

            {% endfor %}
            <div class="card-footer">
                <small class="text-muted">Опубліковано {{ post.publish }}. Автор {{ post.author }}</small>
            </div>
        </div>
    </div>

<h2>Similar POsts</h2>
{% for post in similar_posts %}
    <p>
        <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
    </p>
{% empty %}
    There are no similar posts yet.
{% endfor %}

    {% with comments.count as total_comments  %}
    <h2>{{ total_comments }} коментарiв</h2>
{% endwith %}

{% for comment in comments %}
    <div class='card border-dark mb-3'>
        <div class='card-header'><b>{{ forloop.counter }}. </b> {{ comment.name }}, Email {{ comment.email }}</div>
        <div class='card-body text-dark'>
            <p class='card-text'>{{ comment.body }}</p>
        </div>
    </div>
{% endfor %}
    <div class="m-5">
                    {% if new_comment %}
                        <h2>Ваш комментарий добавлен</h2>
                    {% else %}
                        <h2>Добавить комментарий</h2>
                        <form action="." method="post">
                        <div class="form-group">
                            <label for="nameInput">Имя</label>
                            {{ comment_form.name }}
                        </div>
                        <div class="form-group">
                            <label for="exampleInputEmail1">Ваш Email </label>
                            {{ comment_form.email }}
                        </div>
                        <div class="form-group">
                            <label for="comment">Комментарий</label>
                            {{ comment_form.comment }}
                        </div>
                        <button type="submit" class="btn btn-primary">Добавить комментарий</button>
                        {% csrf_token %}
                        </form>
                    {% endif %}
                </div>
</div>

    {% comment %} <h1> {{ post.title }}</h1>
    <p class='date'>Опубліковано {{ post.publish }} Автором {{ post.author }}</p> {% endcomment %}

{% endblock content %}

mysite/blog/templates/blog/post/list.html
{% extends "blog/base.html" %}
{% block title %}My blog{% endblock title %}
{% block content %}
    {% comment %} <h1>My Blog</h1>
    {% for post in posts %}
        <h2> 
            <a href='{{ post.get_absolute_url }}'>{{ post.title }}</a>
        </h2>
        <p>{{post.short_description}}</p>
        <p class='date'>Опубліковано {{post.publish}} автор : {{post.author}}</p>
        {{ post.body|truncatewords:30|linebreaks}}
    {% endfor %} {% endcomment %}

    <h1 class="title text-center my-3">Кулінарна книга</h1> 

    <div class="container">
        {% if tag %}
            <h2 class='text-center'> Теги: "{{ tag.name }}" </h2>
        {% endif %}
        <div class="card-deck">
            {% for post in posts %}
                <div class="card">
                    <a href={{ post.get_absolute_url}}>
                        <img src="{{ MEDIA_URL }}{{ post.image.url }}" class="card-img-top" alt="...">
                    </a>
                    <div class="card-body">
                        <a href={{ post.get_absolute_url}}>
                            <h5 class="card-title">{{ post.title}}</h5>
                        </a>
                        <p class="card-text">{{ post.short_description}}</p>
                    </div>
                    <div class="card-footer">
                        <small class="text-muted">Опубліковано {{ post.publish }}. Автор {{ post.author }}</small>
                        <p> 
                            {% for tag in post.tags.all %}
                                <a href-"(% url "blog:post_list_by_tag" tag.slug %)">
                                    {{ tag.name }}
                                </a>
                                {% if forloop.last %}, {% endif %}
                            {% endfor %}


                        </p>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>

    {% include "paginations.html" with page=page_obj %}

{% endblock content %}

mysite/blog/templates/blog/post/share.html
{% extends "blog/base.html" %}
{% block title %}Share Post{% endblock title %}

{% block content %}
    {% if sent%}
        <h1>E-mail успішно відправлено</h1>
        <p>"{{ post.title}}" було успішно відправлено {{ form.cleaned_data.to }}.</p>

    {% else %}
        <h1>"{{ post.title }}" Відправлено по e-mail</h1>
        <form action='.', method='post'>

            <div class-'form-group'>
                <label for='nameInput'>Ім'я </label>
                {{ form.name }}
            </div>

            <div class-'form-group'>
                <label for='exampleInputEmail'>Ваш Email</label>
                {{ form.email }}
                <small id='emailHelp' class='form-text text-muted'>Ми не розголошуємо дані наших користувачів</small>
            </div>

            <div class-'form-group'>
                <label for='emailTo'>E-mail отримувач</label>
                {{ form.to }}
            </div>

            <div class-'form-group'>
                <label for='comment'>Коментар</label>
                {{ form.comment }}
            </div>

           <button type='submit' class='btn btn-primary'>Відправити</buttom>
            {% csrf_token %}
        </form>

    {% endif %}

{% endblock content %}

mysite/blog/templates/paginations.html
<div class='pagination'>
    <span class='step-links'>
        {% if page.has_previous %}
            <a href='?page={{page.previous_page_number}}'>Попередня</a>
        {% endif %}
        <span class='current'>
            Сторінка {{ page.number }} із {{ page.paginator.num_pages }}
        </span>
        {% if page.has_next %}
            <a href='?page={{page.next_page_number}}'>Наступна</a>
    {% endif %}
    </span>
</div>